package com.runiversityadmisson.bot.bot.session;

public enum SessionState {
	NEW,
	WAITING_FOR_LANGUAGE,
	WAITING_FOR_CITIZENSHIP,
	WAITING_FOR_EGE_SUBJECT,
	WAITING_FOR_EGE_SCORE,
	WAITING_FOR_EGE_MORE,
	READY_FOR_MINAPP
}
